/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	corev1alpha1 "github.com/nevidanniu/sample-apispec/client-go/applyconfigurations/core/v1alpha1"
	scheme "github.com/nevidanniu/sample-apispec/client-go/ssp/scheme"
	v1alpha1 "github.com/nevidanniu/sample-apispec/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TenantsGetter has a method to return a TenantInterface.
// A group's client should implement this interface.
type TenantsGetter interface {
	Tenants() TenantInterface
}

// TenantInterface has methods to work with Tenant resources.
type TenantInterface interface {
	Create(ctx context.Context, tenant *v1alpha1.Tenant, opts v1.CreateOptions) (*v1alpha1.Tenant, error)
	Update(ctx context.Context, tenant *v1alpha1.Tenant, opts v1.UpdateOptions) (*v1alpha1.Tenant, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Tenant, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TenantList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Tenant, err error)
	Apply(ctx context.Context, tenant *corev1alpha1.TenantApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Tenant, err error)
	TenantExpansion
}

// tenants implements TenantInterface
type tenants struct {
	client rest.Interface
}

// newTenants returns a Tenants
func newTenants(c *CoreV1alpha1Client) *tenants {
	return &tenants{
		client: c.RESTClient(),
	}
}

// Get takes name of the tenant, and returns the corresponding tenant object, and an error if there is any.
func (c *tenants) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Tenant, err error) {
	result = &v1alpha1.Tenant{}
	err = c.client.Get().
		Resource("tenants").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Tenants that match those selectors.
func (c *tenants) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TenantList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TenantList{}
	err = c.client.Get().
		Resource("tenants").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tenants.
func (c *tenants) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("tenants").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a tenant and creates it.  Returns the server's representation of the tenant, and an error, if there is any.
func (c *tenants) Create(ctx context.Context, tenant *v1alpha1.Tenant, opts v1.CreateOptions) (result *v1alpha1.Tenant, err error) {
	result = &v1alpha1.Tenant{}
	err = c.client.Post().
		Resource("tenants").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tenant).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a tenant and updates it. Returns the server's representation of the tenant, and an error, if there is any.
func (c *tenants) Update(ctx context.Context, tenant *v1alpha1.Tenant, opts v1.UpdateOptions) (result *v1alpha1.Tenant, err error) {
	result = &v1alpha1.Tenant{}
	err = c.client.Put().
		Resource("tenants").
		Name(tenant.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tenant).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the tenant and deletes it. Returns an error if one occurs.
func (c *tenants) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("tenants").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tenants) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("tenants").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched tenant.
func (c *tenants) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Tenant, err error) {
	result = &v1alpha1.Tenant{}
	err = c.client.Patch(pt).
		Resource("tenants").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied tenant.
func (c *tenants) Apply(ctx context.Context, tenant *corev1alpha1.TenantApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Tenant, err error) {
	if tenant == nil {
		return nil, fmt.Errorf("tenant provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(tenant)
	if err != nil {
		return nil, err
	}
	name := tenant.Name
	if name == nil {
		return nil, fmt.Errorf("tenant.Name must be provided to Apply")
	}
	result = &v1alpha1.Tenant{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("tenants").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
