/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	ldapv1alpha1 "github.com/nevidanniu/sample-apispec/client-go/applyconfigurations/ldap/v1alpha1"
	v1alpha1 "github.com/nevidanniu/sample-apispec/ldap/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeUsers implements UserInterface
type FakeUsers struct {
	Fake *FakeLdapV1alpha1
}

var usersResource = schema.GroupVersionResource{Group: "ldap.ssp.group", Version: "v1alpha1", Resource: "users"}

var usersKind = schema.GroupVersionKind{Group: "ldap.ssp.group", Version: "v1alpha1", Kind: "User"}

// Get takes name of the user, and returns the corresponding user object, and an error if there is any.
func (c *FakeUsers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.User, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(usersResource, name), &v1alpha1.User{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.User), err
}

// List takes label and field selectors, and returns the list of Users that match those selectors.
func (c *FakeUsers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.UserList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(usersResource, usersKind, opts), &v1alpha1.UserList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.UserList{ListMeta: obj.(*v1alpha1.UserList).ListMeta}
	for _, item := range obj.(*v1alpha1.UserList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested users.
func (c *FakeUsers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(usersResource, opts))
}

// Create takes the representation of a user and creates it.  Returns the server's representation of the user, and an error, if there is any.
func (c *FakeUsers) Create(ctx context.Context, user *v1alpha1.User, opts v1.CreateOptions) (result *v1alpha1.User, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(usersResource, user), &v1alpha1.User{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.User), err
}

// Update takes the representation of a user and updates it. Returns the server's representation of the user, and an error, if there is any.
func (c *FakeUsers) Update(ctx context.Context, user *v1alpha1.User, opts v1.UpdateOptions) (result *v1alpha1.User, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(usersResource, user), &v1alpha1.User{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.User), err
}

// Delete takes name of the user and deletes it. Returns an error if one occurs.
func (c *FakeUsers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(usersResource, name, opts), &v1alpha1.User{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUsers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(usersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.UserList{})
	return err
}

// Patch applies the patch and returns the patched user.
func (c *FakeUsers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.User, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(usersResource, name, pt, data, subresources...), &v1alpha1.User{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.User), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied user.
func (c *FakeUsers) Apply(ctx context.Context, user *ldapv1alpha1.UserApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.User, err error) {
	if user == nil {
		return nil, fmt.Errorf("user provided to Apply must not be nil")
	}
	data, err := json.Marshal(user)
	if err != nil {
		return nil, err
	}
	name := user.Name
	if name == nil {
		return nil, fmt.Errorf("user.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(usersResource, *name, types.ApplyPatchType, data), &v1alpha1.User{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.User), err
}
