/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TenantMemberApplyConfiguration represents an declarative configuration of the TenantMember type for use
// with apply.
type TenantMemberApplyConfiguration struct {
	User *string `json:"user,omitempty"`
	Role *string `json:"role,omitempty"`
}

// TenantMemberApplyConfiguration constructs an declarative configuration of the TenantMember type for use with
// apply.
func TenantMember() *TenantMemberApplyConfiguration {
	return &TenantMemberApplyConfiguration{}
}

// WithUser sets the User field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the User field is set to the value of the last call.
func (b *TenantMemberApplyConfiguration) WithUser(value string) *TenantMemberApplyConfiguration {
	b.User = &value
	return b
}

// WithRole sets the Role field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Role field is set to the value of the last call.
func (b *TenantMemberApplyConfiguration) WithRole(value string) *TenantMemberApplyConfiguration {
	b.Role = &value
	return b
}
